### ISSUE TITLE
orders / option "immediate_or_cancel" not working

### ISSUE THREAD

**Issue by ripplejnr** [ripple/ripple-rest#395] opened 2015-09-22 19:57 UTC
orders/ "immediate_or_cancel" flag not working. 

As far as I can tell, I am setting this parameter correct to true, but in the transaction it turns up as false and the order is placed in the ledger.

**Comment by clark800** [comment] 2015-09-22 22:02
I'm unable to reproduce. Can you provide explicit instructions for reproducing the issue?

**Comment by ripplejnr** [comment] 2015-09-25 21:08
When the order is placed (it is placed...which should not if I understand correct), then the value "immediate_or_cancel" is false. 
I'm using the following code (in bash shell script on linux):

# Trade account (fill in your account)
TRADE_ACCOUNT="xxx"

# USD.SnapSwap
TAKER_GETS_CURRENCY=USD
TAKER_GETS_COUNTERPARTY="rMwjYedjc7qqtKYVLiAccJSmCwih4LnE2q"

# USD.Bitstamp
TAKER_PAYS_CURRENCY=USD
TAKER_PAYS_COUNTERPARTY="rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B"

# USD.SnapSwap
TAKER_GETS_VALUE=$(awk 'BEGIN { printf "%.6f", ('$AMOUNT') }')

# USD.Bitstamp
TAKER_PAYS_VALUE=$(awk 'BEGIN { printf "%.6f", ('$PRICE'*'$AMOUNT') }')

# Secret (fill in secret)
SECRET="xxx"

ORDER_PARAMS='
{
    "secret" : "'$SECRET'",
    "immediate_or_cancel" : true,
    "order" : {
        "type" : "sell",
        "taker_pays" : {
            "currency" : "'$TAKER_PAYS_CURRENCY'",
            "counterparty" : "'$TAKER_PAYS_COUNTERPARTY'",
            "value" : "'$TAKER_PAYS_VALUE'"
        },
        "taker_gets" : {
            "currency" : "'$TAKER_GETS_CURRENCY'",
            "counterparty" : "'$TAKER_GETS_COUNTERPARTY'",
            "value" : "'$TAKER_GETS_VALUE'"
        }
    }
}'

RESULT=$(curl   -s \
        -k \
        -H Content-Type:application/json \
        -H application/json \
        -X POST \
        -d $ORDER_PARAMS \
        https://127.0.0.1:5990/v1/accounts/$TRADE_ACCOUNT/orders?validated=true)

**Comment by clark800** [comment] 2015-09-26 00:12
In your script, `immediate_or_cancel` is outside the `order` object. Try moving it inside the `order` object.

**Comment by ripplejnr** [comment] 2015-09-26 07:45
ok thanks! I have tried and it works :+1: 
sorry if it's not a bug ;-) sometimes hard to tell where to place an issue. I guess in this case it would better be phrased as a question on the forum..
Thanks again for your help

rgds.
Jarl

**Closed** 2015-09-28 17:22 UTC
